import { Router } from "express";
import { authMiddleware } from "../../middleware/auth.middleware";
import { requirePermission } from "../../middleware/permission.middleware";
import { allowRoles } from "../../middleware/rbac.middleware";
import { attendanceLimiter } from "../../middleware/rateLimiter.middleware";
import { validate } from "../../middleware/validate.middleware";
import { allowOnlyClassTeacher } from "@/middleware/classTeacher.middleware";
import { attendanceContext, create, listAudit, schoolSummary, studentMonthlySummary, teacherContext, update, } from "@/modules/attendance/controller";
import correctionsRouter from "@/modules/attendance/corrections/routes";
import { attendanceAuditQuerySchema, attendanceIdParamSchema, createAttendanceSchema, schoolSummaryQuerySchema, studentMonthlySummaryQuerySchema, updateAttendanceSchema, } from "@/modules/attendance/validation";
const attendanceRouter = Router();
attendanceRouter.use(attendanceLimiter);
attendanceRouter.post("/", authMiddleware, allowRoles("TEACHER"), requirePermission("attendance:mark"), validate(createAttendanceSchema), allowOnlyClassTeacher, create);
attendanceRouter.get("/context", authMiddleware, allowRoles("TEACHER"), requirePermission("attendance:mark"), attendanceContext);
attendanceRouter.patch("/:id", authMiddleware, allowRoles("TEACHER"), requirePermission("attendance:update"), validate({ params: attendanceIdParamSchema, body: updateAttendanceSchema }), allowOnlyClassTeacher, update);
attendanceRouter.get("/class-teacher/context", authMiddleware, allowRoles("TEACHER"), requirePermission("attendance:mark"), teacherContext);
attendanceRouter.get("/audit", authMiddleware, requirePermission("attendance:read"), validate({ query: attendanceAuditQuerySchema }), listAudit);
attendanceRouter.get("/summaries/student", authMiddleware, requirePermission("attendance:read"), validate({ query: studentMonthlySummaryQuerySchema }), studentMonthlySummary);
attendanceRouter.get("/summaries/school", authMiddleware, requirePermission("attendance:read"), validate({ query: schoolSummaryQuerySchema }), schoolSummary);
attendanceRouter.use("/corrections", correctionsRouter);
export default attendanceRouter;
