import type { RoleType } from "../types/auth";

export type FeatureCategory =
  | "CORE"
  | "ACADEMIC"
  | "ADMIN CONTROL"
  | "SYSTEM"
  | "FINANCE"
  | "ANALYTICS";

export type FeatureItem = {
  key: string;
  label: string;
  path: string;
  roles: RoleType[];
  description: string;
  category: FeatureCategory;
  page:
  | { type: "existing" }
  | {
    type: "resource";
    endpoint: string;
    columns?: Array<string | { key: string; label: string }>;
    primaryKey?: string;
  }
  | { type: "coming-soon" };
};

export type FeatureGroup = {
  title: FeatureCategory;
  items: FeatureItem[];
};

const ADMIN_ONLY: RoleType[] = ["ADMIN", "SUPER_ADMIN"];

export const featureGroups: FeatureGroup[] = [
  {
    title: "CORE",
    items: [
      {
        key: "dashboard",
        label: "Dashboard",
        path: "/",
        roles: [
          "ADMIN",
          "ACADEMIC_SUB_ADMIN",
          "SUPER_ADMIN",
          "TEACHER",
          "STUDENT",
          "PARENT",
          "FINANCE_SUB_ADMIN",
        ],
        description: "Role-based dashboards for daily operations.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "classroom",
        label: "Classroom",
        path: "/classroom",
        roles: ["TEACHER", "STUDENT", "PARENT"],
        description: "Assignments, notes, and classroom chat in one place.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "teacher-profile",
        label: "My Profile",
        path: "/teacher/profile",
        roles: ["TEACHER"],
        description: "Update qualifications, experience, and publications.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "teacher-promotions",
        label: "Promotions",
        path: "/teacher/promotions",
        roles: ["TEACHER"],
        description: "Review and approve under-consideration promotions.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "teacher-leave",
        label: "My Leaves",
        path: "/teacher/leave",
        roles: ["TEACHER"],
        description: "Apply for leave and track approvals.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "teacher-history",
        label: "Teaching History",
        path: "/teacher/history",
        roles: ["TEACHER"],
        description: "Review academic-year assignments and history.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "student-leave",
        label: "My Leaves",
        path: "/student/leave",
        roles: ["STUDENT"],
        description: "Apply for leave and track approvals.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "student-promotions",
        label: "Promotion Status",
        path: "/student/promotion",
        roles: ["STUDENT"],
        description: "View your promotion result and next class.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "student-history",
        label: "Academic History",
        path: "/student/history",
        roles: ["STUDENT"],
        description: "View academic history across previous years.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "exam-routine-student",
        label: "Exam Routine",
        path: "/exam/routine",
        roles: ["STUDENT", "PARENT"],
        description: "View published exam schedules and rooms.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "certificates",
        label: "Certificates",
        path: "/certificates",
        roles: ["STUDENT", "PARENT"],
        description: "Request and download certificates.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "id-card",
        label: "ID Card",
        path: "/id-card",
        roles: ["STUDENT", "PARENT"],
        description: "View and print your digital ID card.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "student-fees",
        label: "Fees & Payments",
        path: "/fees",
        roles: ["STUDENT", "PARENT"],
        description: "View fee status, pay dues, and access receipts.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "teacher-id-card",
        label: "ID Card",
        path: "/teacher/id-card",
        roles: ["TEACHER"],
        description: "View and print your faculty ID card.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "exam-registration",
        label: "Exam Registration",
        path: "/exam/registration",
        roles: ["STUDENT", "PARENT"],
        description: "Register for exams after fee payment.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "parent-leave",
        label: "Student Leaves",
        path: "/parent/leave",
        roles: ["PARENT"],
        description: "Apply leave on behalf of your child.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "parent-promotions",
        label: "Promotion Status",
        path: "/parent/promotion",
        roles: ["PARENT"],
        description: "Track your child’s promotion outcome.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "parent-history",
        label: "Academic History",
        path: "/parent/history",
        roles: ["PARENT"],
        description: "View your child’s academic history.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "students",
        label: "Students",
        path: "/admin/students",
        roles: ADMIN_ONLY,
        description: "Student profiles, enrollment, transfers, and bulk imports.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/students",
          columns: [
            { key: "fullName", label: "Student" },
            { key: "registrationNumber", label: "Reg. No." },
            { key: "admissionNumber", label: "Admission No." },
            { key: "status", label: "Status" },
            { key: "enrollments.0.class.className", label: "Class" },
            { key: "enrollments.0.section.sectionName", label: "Section" },
          ],
        },
      },
      {
        key: "student-imports",
        label: "Student Bulk Import",
        path: "/admin/students/imports",
        roles: ADMIN_ONLY,
        description: "Excel import pipeline with validation and preview.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "teachers",
        label: "Teachers",
        path: "/admin/teachers",
        roles: ADMIN_ONLY,
        description: "Teacher profiles, assignments, and activation.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/teachers",
          columns: [
            { key: "fullName", label: "Teacher" },
            { key: "employeeId", label: "Employee ID" },
            { key: "designation", label: "Designation" },
            { key: "phone", label: "Phone" },
            { key: "status", label: "Status" },
          ],
        },
      },
      {
        key: "teacher-imports",
        label: "Teacher Bulk Import",
        path: "/admin/teachers/imports",
        roles: ADMIN_ONLY,
        description: "Teacher Excel imports with subject/class mapping.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "parents",
        label: "Parents",
        path: "/admin/parents",
        roles: ADMIN_ONLY,
        description: "Parent accounts and student links.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "admin-student-leaves",
        label: "Student Leaves",
        path: "/admin/student-leaves",
        roles: ADMIN_ONLY,
        description: "Review and approve student leave requests.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "admin-teacher-leaves",
        label: "Teacher Leaves",
        path: "/admin/teacher-leaves",
        roles: ADMIN_ONLY,
        description: "Review and approve teacher leave requests.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "academic-years",
        label: "Academic Years",
        path: "/admin/academic-years",
        roles: ADMIN_ONLY,
        description: "Academic year setup and rollover.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/academic-years",
          columns: [
            { key: "label", label: "Year" },
            { key: "startDate", label: "Start" },
            { key: "endDate", label: "End" },
            { key: "isActive", label: "Active" },
            { key: "isLocked", label: "Locked" },
          ],
        },
      },
      {
        key: "classes",
        label: "Classes",
        path: "/admin/classes",
        roles: ADMIN_ONLY,
        description: "Class master data and capacity limits.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/classes",
          columns: [
            { key: "className", label: "Class" },
            { key: "classOrder", label: "Order" },
            { key: "isHalfDay", label: "Half Day" },
            { key: "academicYear.label", label: "Academic Year" },
          ],
        },
      },
      {
        key: "sections",
        label: "Sections",
        path: "/admin/sections",
        roles: ADMIN_ONLY,
        description: "Section setup with class teacher mapping.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/sections",
          columns: [
            { key: "sectionName", label: "Section" },
            { key: "capacity", label: "Capacity" },
            { key: "class.className", label: "Class" },
          ],
        },
      },
      {
        key: "subjects",
        label: "Subjects",
        path: "/admin/subjects",
        roles: ADMIN_ONLY,
        description: "Subject library and class mappings.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/subjects",
          columns: [
            { key: "code", label: "Code" },
            { key: "name", label: "Subject" },
            { key: "isElective", label: "Elective" },
          ],
        },
      },
      {
        key: "class-subjects",
        label: "Class Subjects",
        path: "/admin/class-subjects",
        roles: ADMIN_ONLY,
        description: "Select subjects taught in each class.",
        category: "CORE",
        page: { type: "existing" },
      },
      {
        key: "periods",
        label: "Periods",
        path: "/admin/periods",
        roles: ADMIN_ONLY,
        description: "Period counts, durations, and lunch configuration.",
        category: "CORE",
        page: {
          type: "resource",
          endpoint: "/periods",
          columns: [
            { key: "periodNumber", label: "Period" },
            { key: "startTime", label: "Start" },
            { key: "endTime", label: "End" },
            { key: "isLunch", label: "Lunch" },
          ],
        },
      },
    ],
  },
  {
    title: "ACADEMIC",
    items: [
      {
        key: "attendance",
        label: "Attendance",
        path: "/attendance",
        roles: ["STUDENT", "PARENT"],
        description: "Daily attendance and summaries.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "student-timetable",
        label: "My Timetable",
        path: "/student/timetable",
        roles: ["STUDENT"],
        description: "Weekly class timetable.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "parent-timetable",
        label: "Child Timetable",
        path: "/parent/timetable",
        roles: ["PARENT"],
        description: "Child's weekly class timetable.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "attendance-teacher",
        label: "Attendance",
        path: "/teacher/attendance",
        roles: ["TEACHER"],
        description: "Class teacher attendance panel.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "marks-entry",
        label: "Marks",
        path: "/marks",
        roles: ["TEACHER"],
        description: "Marks entry for assigned exams.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "teacher-analytics",
        label: "Student Analytics",
        path: "/teacher/analytics",
        roles: ["TEACHER"],
        description: "Section analytics for exams.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "timetable-slots",
        label: "Timetable",
        path: "/admin/timetable",
        roles: ADMIN_ONLY,
        description: "Timetable slots and scheduling rules.",
        category: "ACADEMIC",
        page: {
          type: "resource",
          endpoint: "/timetable-slots",
          columns: [
            { key: "classSubject.class.className", label: "Class" },
            { key: "classSubject.subject.name", label: "Subject" },
            { key: "section.sectionName", label: "Section" },
            { key: "dayOfWeek", label: "Day" },
            { key: "period.periodNumber", label: "Period" },
          ],
        },
      },
      {
        key: "academic-calendar",
        label: "Academic Calendar",
        path: "/admin/academic-calendar",
        roles: ADMIN_ONLY,
        description: "Session dates, holidays, exams, and academic notices.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "exams",
        label: "Exams",
        path: "/exams",
        roles: ["ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"],
        description: "Exam terms, timetable, and configuration.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "results",
        label: "Results",
        path: "/results",
        roles: ["ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN", "STUDENT", "PARENT"],
        description: "Exam results and publishing.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
      {
        key: "ranking",
        label: "Student Rank",
        path: "/ranking",
        roles: ["ADMIN", "SUPER_ADMIN", "ACADEMIC_SUB_ADMIN", "TEACHER", "STUDENT"],
        description: "Rank snapshots and analytics.",
        category: "ACADEMIC",
        page: { type: "existing" },
      },
    ],
  },
  {
    title: "ADMIN CONTROL",
    items: [
      {
        key: "notices",
        label: "Notices",
        path: "/notices",
        roles: [
          "ADMIN",
          "ACADEMIC_SUB_ADMIN",
          "SUPER_ADMIN",
          "TEACHER",
          "STUDENT",
          "PARENT",
          "FINANCE_SUB_ADMIN",
        ],
        description: "School notice board and announcements.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "certificate-requests",
        label: "Certificate Requests",
        path: "/admin/certificates",
        roles: ADMIN_ONLY,
        description: "Approve or reject certificate requests.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "tc-generator",
        label: "TC Generator",
        path: "/admin/tc-generator",
        roles: ADMIN_ONLY,
        description: "Generate transfer certificates and expel students.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "digital-id",
        label: "Digital Student ID",
        path: "/admin/digital-id",
        roles: ADMIN_ONLY,
        description: "QR-based student ID cards.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "teacher-id-cards",
        label: "Digital Teacher ID",
        path: "/admin/teachers/id-cards",
        roles: ADMIN_ONLY,
        description: "Faculty identity cards and printing.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "admissions",
        label: "Admission & Lottery",
        path: "/admin/admissions",
        roles: ADMIN_ONLY,
        description: "Online admission and lottery workflow.",
        category: "ADMIN CONTROL",
        page: { type: "coming-soon" },
      },
      {
        key: "substitution",
        label: "Substitution",
        path: "/admin/substitution",
        roles: ADMIN_ONLY,
        description: "Teacher substitution management.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "promotion-system",
        label: "Promotion System",
        path: "/admin/promotions",
        roles: ADMIN_ONLY,
        description: "Year-end promotion and section allotment.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
      {
        key: "promotion-overview",
        label: "Promotion Overview",
        path: "/admin/promotions/overview",
        roles: ADMIN_ONLY,
        description: "Published promotion summary and outcomes.",
        category: "ADMIN CONTROL",
        page: { type: "existing" },
      },
    ],
  },
  {
    title: "FINANCE",
    items: [
      {
        key: "fees",
        label: "Fee Structure",
        path: "/admin/fees",
        roles: ADMIN_ONLY,
        description: "Create and publish fee structures.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "fees-overview",
        label: "Fee Overview",
        path: "/admin/fees/overview",
        roles: ["ADMIN", "SUPER_ADMIN", "FINANCE_SUB_ADMIN"],
        description: "Collections analytics and finance insights.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "scholarships",
        label: "Scholarships",
        path: "/admin/scholarships",
        roles: ADMIN_ONLY,
        description: "Manage scholarships and student fee relief.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "discounts",
        label: "Discounts",
        path: "/admin/discounts",
        roles: ADMIN_ONLY,
        description: "Create and review discount records.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "fee-paid-unpaid",
        label: "Fee Paid/Unpaid",
        path: "/admin/fee-payments",
        roles: ADMIN_ONLY,
        description: "Track paid and unpaid students.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "admit-card-admin",
        label: "Admit Card Publish",
        path: "/admin/admit-cards",
        roles: ADMIN_ONLY,
        description: "Publish admit cards and view records.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "exam-registrations-admin",
        label: "Exam Registrations",
        path: "/admin/exam-registrations",
        roles: ADMIN_ONLY,
        description: "View registered students per exam.",
        category: "FINANCE",
        page: { type: "existing" },
      },
      {
        key: "payment-logs",
        label: "Payment Logs",
        path: "/admin/payments/logs",
        roles: ["ADMIN", "SUPER_ADMIN", "FINANCE_SUB_ADMIN"],
        description: "Audit payment attempts (success and failure).",
        category: "FINANCE",
        page: { type: "existing" },
      },
    ],
  },
  {
    title: "SYSTEM",
    items: [
      {
        key: "admin-records",
        label: "Records / Archive",
        path: "/admin/records",
        roles: ADMIN_ONLY,
        description: "Browse archived academic years and historical records.",
        category: "SYSTEM",
        page: { type: "existing" },
      },
      {
        key: "settings",
        label: "Settings",
        path: "/admin/settings",
        roles: ADMIN_ONLY,
        description: "School configuration, integrations, and policies.",
        category: "SYSTEM",
        page: { type: "existing" },
      },
      {
        key: "school-overview",
        label: "School Overview",
        path: "/admin/settings/school-overview",
        roles: ADMIN_ONLY,
        description: "Branding and identity settings for the school.",
        category: "SYSTEM",
        page: { type: "existing" },
      },
      {
        key: "notifications",
        label: "Notifications",
        path: "/notifications",
        roles: [
          "ADMIN",
          "ACADEMIC_SUB_ADMIN",
          "SUPER_ADMIN",
          "FINANCE_SUB_ADMIN",
          "TEACHER",
          "STUDENT",
          "PARENT",
        ],
        description: "In-app notifications and inbox.",
        category: "SYSTEM",
        page: { type: "existing" },
      },
    ],
  },
];

export const allFeatures = featureGroups.flatMap((group) => group.items);

export const adminOnlyFeatures = allFeatures.filter(
  (item) => item.roles.every((role) => ADMIN_ONLY.includes(role))
);
