import { Router } from "express";
import { authMiddleware } from "@/middleware/auth.middleware";
import { allowRoles } from "@/middleware/rbac.middleware";
import { requirePermission } from "@/middleware/permission.middleware";
import { validate } from "@/middleware/validate.middleware";
import { bulkCreate, sectionTimetable, teacherTimetable, teacherToday, validateSlot, studentTimetable, parentTimetable, deleteSlot, substitute, lockTimetable, unlockTimetable, timetableLockStatus, timetableMeta, timetableWorkload, timetableOptions, } from "@/modules/timetable/controller";
import { bulkCreateTimetableSchema, deleteTimetableSlotSchema, sectionTimetableParamSchema, substituteTimetableSchema, teacherTimetableParamSchema, teacherTimetableQuerySchema, timetableMetaParamSchema, timetableOptionsQuerySchema, timetableDateQuerySchema, validateTimetableSlotSchema, } from "@/modules/timetable/validation";
const timetableRouter = Router();
timetableRouter.post("/admin/timetable/bulk-create", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:create"), validate(bulkCreateTimetableSchema), bulkCreate);
timetableRouter.post("/admin/timetable/lock", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:update"), lockTimetable);
timetableRouter.post("/admin/timetable/unlock", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:update"), unlockTimetable);
timetableRouter.get("/admin/timetable/lock-status", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:read"), timetableLockStatus);
timetableRouter.get("/admin/timetable/meta/:sectionId", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:read"), validate({ params: timetableMetaParamSchema }), timetableMeta);
timetableRouter.get("/admin/timetable/options", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:read"), validate({ query: timetableOptionsQuerySchema }), timetableOptions);
timetableRouter.get("/admin/timetable/workload", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:read"), timetableWorkload);
timetableRouter.post("/admin/timetable/validate-slot", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:create"), validate(validateTimetableSlotSchema), validateSlot);
timetableRouter.delete("/admin/timetable/slot", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:delete"), validate(deleteTimetableSlotSchema), deleteSlot);
timetableRouter.post("/admin/timetable/substitute", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN"), requirePermission("timetableSlot:update"), validate(substituteTimetableSchema), substitute);
timetableRouter.get("/timetable/section/:sectionId", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN", "TEACHER", "STUDENT", "PARENT"), requirePermission("timetableSlot:read"), validate({ params: sectionTimetableParamSchema, query: timetableDateQuerySchema }), sectionTimetable);
timetableRouter.get("/timetable/teacher/:teacherId", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN", "SUPER_ADMIN", "TEACHER"), requirePermission("timetableSlot:read"), validate({ params: teacherTimetableParamSchema, query: teacherTimetableQuerySchema }), teacherTimetable);
timetableRouter.get("/timetable/teacher/today", authMiddleware, allowRoles("TEACHER"), requirePermission("timetableSlot:read"), teacherToday);
timetableRouter.get("/timetable/student/me", authMiddleware, allowRoles("STUDENT"), requirePermission("timetableSlot:read"), studentTimetable);
timetableRouter.get("/timetable/parent/me", authMiddleware, allowRoles("PARENT"), requirePermission("timetableSlot:read"), parentTimetable);
export default timetableRouter;
