import { vi } from "vitest";

export function createMockPrisma() {
  return {
    academicYear: { findFirst: vi.fn(), findMany: vi.fn() },
    admitCard: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      createMany: vi.fn(),
      update: vi.fn(),
      deleteMany: vi.fn(),
    },
    auditLog: { create: vi.fn(), findMany: vi.fn() },
    attendanceAuditLog: { create: vi.fn(), createMany: vi.fn() },
    attendanceCorrection: { create: vi.fn(), findFirst: vi.fn(), update: vi.fn() },
    class: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn() },
    classSubject: { create: vi.fn(), findFirst: vi.fn(), findMany: vi.fn(), count: vi.fn() },
    circular: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      count: vi.fn(),
    },
    exam: { findFirst: vi.fn(), findMany: vi.fn(), update: vi.fn(), count: vi.fn() },
    examSubject: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      createMany: vi.fn(),
    },
    examTimetable: { findFirst: vi.fn(), findMany: vi.fn() },
    feeDeadline: { findMany: vi.fn() },
    feeTerm: { findFirst: vi.fn() },
    mark: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      createMany: vi.fn(),
      update: vi.fn(),
    },
    markEditLog: { create: vi.fn() },
    notificationJob: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      findUnique: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      updateMany: vi.fn(),
    },
    noticeBoard: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      count: vi.fn(),
    },
    notification: { create: vi.fn() },
    notificationRecipient: { createMany: vi.fn(), findMany: vi.fn(), count: vi.fn(), updateMany: vi.fn() },
    otpLog: { findFirst: vi.fn(), create: vi.fn() },
    parent: { findFirst: vi.fn(), create: vi.fn() },
    parentStudentLink: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn() },
    payment: { findMany: vi.fn() },
    period: { findFirst: vi.fn(), count: vi.fn() },
    rankSnapshot: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      createMany: vi.fn(),
      deleteMany: vi.fn(),
      count: vi.fn(),
    },
    reportCard: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      updateMany: vi.fn(),
      upsert: vi.fn(),
      deleteMany: vi.fn(),
      count: vi.fn(),
    },
    school: { findFirst: vi.fn(), findUnique: vi.fn() },
    section: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn() },
    session: { create: vi.fn() },
    student: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      count: vi.fn(),
    },
    studentAttendance: {
      findMany: vi.fn(),
      findFirst: vi.fn(),
      create: vi.fn(),
      createMany: vi.fn(),
      groupBy: vi.fn(),
      update: vi.fn(),
      count: vi.fn(),
    },
    studentEnrollment: {
      findMany: vi.fn(),
      findFirst: vi.fn(),
      create: vi.fn(),
      aggregate: vi.fn(),
      count: vi.fn(),
    },
    studentLeave: {
      create: vi.fn(),
      findFirst: vi.fn(),
      findMany: vi.fn(),
      update: vi.fn(),
      count: vi.fn(),
    },
    studentProfile: { findFirst: vi.fn(), create: vi.fn() },
    subject: { findFirst: vi.fn() },
    systemSetting: { findMany: vi.fn() },
    teacher: { create: vi.fn(), findMany: vi.fn(), findFirst: vi.fn(), update: vi.fn(), count: vi.fn() },
    teacherSubjectClass: {
      create: vi.fn(),
      findMany: vi.fn(),
      findFirst: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      count: vi.fn(),
    },
    timetableSlot: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      count: vi.fn(),
    },
    user: { findUnique: vi.fn(), findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    $transaction: vi.fn(),
    $queryRaw: vi.fn(),
  };
}
