export const permissionKeys = [
    "academicYear:create",
    "academicYear:read",
    "academicYear:update",
    "academicYear:delete",
    "academicCalendar:create",
    "academicCalendar:read",
    "academicCalendar:update",
    "academicCalendar:delete",
    "admitCard:generate",
    "admitCard:generatePdf",
    "admitCard:publish",
    "admitCard:read",
    "admitCard:unlock",
    "assignment:create",
    "assignment:delete",
    "assignment:grade",
    "assignment:read",
    "assignment:submit",
    "assignment:update",
    "attendance:mark",
    "attendance:read",
    "attendance:update",
    "circular:create",
    "circular:delete",
    "circular:read",
    "circular:update",
    "class:create",
    "class:read",
    "class:update",
    "class:delete",
    "classSubject:create",
    "classSubject:read",
    "classSubject:update",
    "classSubject:delete",
    "certificate:request",
    "certificate:read",
    "certificate:approve",
    "certificate:reject",
    "tc:generate",
    "exam:create",
    "exam:register",
    "exam:update",
    "exam:publish",
    "exam:lock",
    "exam:read",
    "marks:create",
    "marks:read",
    "marks:update",
    "note:create",
    "note:delete",
    "note:read",
    "note:update",
    "notice:create",
    "notice:read",
    "notice:update",
    "notice:delete",
    "notification:send",
    "notification:read",
    "notification:update",
    "file:write",
    "fee:structure",
    "fee:pay",
    "fee:read",
    "period:create",
    "period:read",
    "period:update",
    "period:delete",
    "ranking:read",
    "ranking:recompute",
    "reportCard:read",
    "result:read",
    "result:publish",
    "result:recompute",
    "section:create",
    "section:read",
    "section:update",
    "section:delete",
    "student:create",
    "student:read",
    "student:update",
    "student:delete",
    "student:bulk-import",
    "studentLeave:create",
    "studentLeave:read",
    "studentLeave:update",
    "subject:create",
    "subject:read",
    "subject:update",
    "subject:delete",
    "settings:read",
    "settings:update",
    "syllabus:create",
    "syllabus:read",
    "syllabus:update",
    "syllabus:delete",
    "teacher:create",
    "teacher:read",
    "teacher:update",
    "teacher:delete",
    "teacher:bulk-import",
    "teacherLeave:create",
    "teacherLeave:read",
    "teacherLeave:update",
    "teacherSubjectClass:create",
    "teacherSubjectClass:read",
    "teacherSubjectClass:update",
    "teacherSubjectClass:delete",
    "timetableSlot:create",
    "timetableSlot:read",
    "timetableSlot:update",
    "timetableSlot:delete",
];
export const permissionDescriptions = {
    "academicCalendar:create": "Create academic calendar events",
    "academicCalendar:read": "Read academic calendar events",
    "academicCalendar:update": "Update academic calendar events",
    "academicCalendar:delete": "Delete academic calendar events",
    "attendance:mark": "Mark student attendance",
    "attendance:update": "Update student attendance",
    "notice:create": "Create notice",
    "notice:read": "Read notices",
    "notice:update": "Update notice",
    "notice:delete": "Delete notice",
    "circular:create": "Create circular",
    "circular:read": "Read circulars",
    "circular:update": "Update circular",
    "circular:delete": "Delete circular",
    "notification:send": "Send notifications",
    "exam:register": "Register for exams",
    "admitCard:publish": "Publish admit cards",
    "fee:structure": "Manage fee structures",
    "fee:pay": "Record fee payments",
    "fee:read": "Read fee status",
    "certificate:request": "Request certificates",
    "certificate:read": "Read certificate requests",
    "certificate:approve": "Approve certificate requests",
    "certificate:reject": "Reject certificate requests",
    "tc:generate": "Generate transfer certificates",
};
