import { Router } from "express";
import { resendOtpController, sendOtpController, verifyOtpController, } from "@/modules/otp/otp.controller";
import { otpLimiter } from "../../middleware/rateLimiter.middleware";
import { validate } from "../../middleware/validate.middleware";
import { resendOtpSchema, sendOtpSchema, verifyOtpSchema, } from "@/modules/otp/otp.validation";
const otpRouter = Router();
otpRouter.post("/send", otpLimiter, validate(sendOtpSchema), sendOtpController);
otpRouter.post("/resend", otpLimiter, validate(resendOtpSchema), resendOtpController);
otpRouter.post("/verify", otpLimiter, validate(verifyOtpSchema), verifyOtpController);
export default otpRouter;
