import { Router } from "express";
import { authMiddleware } from "../../middleware/auth.middleware";
import { requirePermission } from "../../middleware/permission.middleware";
import { allowRoles } from "../../middleware/rbac.middleware";
import { uploadSingle } from "../../middleware/upload.middleware";
import { validate } from "../../middleware/validate.middleware";
import { addAttachment, create, getById, grade, list, listSubmissions, remove, submissionStatus, submit, update, } from "@/modules/assignments/controller";
import { assignmentIdParamSchema, createAssignmentSchema, gradeSubmissionSchema, listAssignmentQuerySchema, listAssignmentSubmissionsQuerySchema, submissionIdParamSchema, submitAssignmentSchema, updateAssignmentSchema, } from "@/modules/assignments/validation";
const assignmentsRouter = Router();
assignmentsRouter.post("/", authMiddleware, allowRoles("TEACHER"), requirePermission("assignment:create"), validate(createAssignmentSchema), create);
assignmentsRouter.get("/", authMiddleware, allowRoles("TEACHER", "STUDENT", "PARENT"), requirePermission("assignment:read"), validate({ query: listAssignmentQuerySchema }), list);
assignmentsRouter.get("/:id", authMiddleware, allowRoles("TEACHER", "STUDENT", "PARENT"), requirePermission("assignment:read"), validate({ params: assignmentIdParamSchema }), getById);
assignmentsRouter.get("/:id/submission-status", authMiddleware, allowRoles("STUDENT", "PARENT"), requirePermission("assignment:read"), validate({ params: assignmentIdParamSchema }), submissionStatus);
assignmentsRouter.patch("/:id", authMiddleware, allowRoles("TEACHER"), requirePermission("assignment:update"), validate({ params: assignmentIdParamSchema, body: updateAssignmentSchema }), update);
assignmentsRouter.post("/:id/attachments", authMiddleware, allowRoles("TEACHER"), requirePermission("assignment:update"), validate({ params: assignmentIdParamSchema }), ...uploadSingle({ module: "assignments", fieldName: "file" }), addAttachment);
assignmentsRouter.delete("/:id", authMiddleware, allowRoles("TEACHER"), requirePermission("assignment:delete"), validate({ params: assignmentIdParamSchema }), remove);
assignmentsRouter.post("/:id/submit", authMiddleware, allowRoles("STUDENT"), requirePermission("assignment:submit"), validate({ params: assignmentIdParamSchema, body: submitAssignmentSchema }), submit);
assignmentsRouter.get("/:id/submissions", authMiddleware, allowRoles("TEACHER"), requirePermission("assignment:read"), validate({ params: assignmentIdParamSchema, query: listAssignmentSubmissionsQuerySchema }), listSubmissions);
assignmentsRouter.patch("/submissions/:id/grade", authMiddleware, allowRoles("TEACHER"), requirePermission("assignment:grade"), validate({ params: submissionIdParamSchema, body: gradeSubmissionSchema }), grade);
export default assignmentsRouter;
