import { Router } from "express";
import { authMiddleware } from "../../middleware/auth.middleware";
import { requirePermission } from "../../middleware/permission.middleware";
import { allowRoles } from "../../middleware/rbac.middleware";
import { validate } from "../../middleware/validate.middleware";
import { create, getById, list, remove, update } from "@/modules/period/controller";
import { createPeriodSchema, listPeriodQuerySchema, periodIdParamSchema, updatePeriodSchema, } from "@/modules/period/validation";
const periodRouter = Router();
periodRouter.post("/", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN"), requirePermission("period:create"), validate(createPeriodSchema), create);
periodRouter.get("/", authMiddleware, validate({ query: listPeriodQuerySchema }), list);
periodRouter.get("/:id", authMiddleware, validate({ params: periodIdParamSchema }), getById);
periodRouter.patch("/:id", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN"), requirePermission("period:update"), validate({ params: periodIdParamSchema, body: updatePeriodSchema }), update);
periodRouter.delete("/:id", authMiddleware, allowRoles("ADMIN", "ACADEMIC_SUB_ADMIN"), requirePermission("period:delete"), validate({ params: periodIdParamSchema }), remove);
export default periodRouter;
